[build]
  command = "npm install --legacy-peer-deps && npm run build -- --configuration production"
  publish = "dist/dream"  # Adjust this if the output path is different

[build.environment]
  NODE_VERSION = "18"

